services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=school
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: